services:
  remix:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - ${PORT}:${PORT}
      - 24678:24678
    env_file:
      - .env
    volumes:
      # bind mount
      - ./app:/remix/app
      - ./server.js:/remix/server.js
      # anonymous volume
      - /remix/node_modules